
package Vista.Boletaje;

import Controlador.ControladorDistibucionBol;
import Controlador.ControladorVehiculo;
import Controlador.Tablas;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ControlBoletos extends javax.swing.JPanel {
    ControladorVehiculo CV = new ControladorVehiculo();
    ControladorDistibucionBol CDB = new ControladorDistibucionBol();
    String CodigoVehiculo;
    
    public ControlBoletos() {
        initComponents();
        lblnom.setText("");
        lblfecha.setText("");
        lblusuario.setText("");
        lblhora.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controlboleto = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb5 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb25 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb12 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tb15 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tb50 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        tb70 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAbastecer = new rojeru_san.RSButton();
        btnLiquidar = new rojeru_san.RSButton();
        btnAnular = new rojeru_san.RSButton();
        btnImprimir = new rojeru_san.RSButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPadron = new rojeru_san.RSMTextFull();
        btnBuscar = new rojeru_san.RSButton();
        lblnom = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlboleto.setBackground(new java.awt.Color(255, 255, 255));
        controlboleto.setBorder(javax.swing.BorderFactory.createTitledBorder("BOLETOS DISPONIBLES"));

        tb4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "4.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb4MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb4);

        tb5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "5.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb5MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb5);

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "3.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb3MousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tb3);

        tb25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb25MousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tb25);

        tb12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.20"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb12MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tb12);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb1MousePressed(evt);
            }
        });
        tb1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb1KeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tb1);

        tb15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "1.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb15MousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(tb15);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "2.00"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb2MousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tb2);

        tb50.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb50MousePressed(evt);
            }
        });
        jScrollPane9.setViewportView(tb50);

        tb70.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "0.70"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb70MousePressed(evt);
            }
        });
        jScrollPane10.setViewportView(tb70);

        javax.swing.GroupLayout controlboletoLayout = new javax.swing.GroupLayout(controlboleto);
        controlboleto.setLayout(controlboletoLayout);
        controlboletoLayout.setHorizontalGroup(
            controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlboletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        controlboletoLayout.setVerticalGroup(
            controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlboletoLayout.createSequentialGroup()
                .addGroup(controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(controlboletoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlboletoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(controlboletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(controlboleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 906, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAbastecer.setBackground(java.awt.Color.lightGray);
        btnAbastecer.setText("ABASTECER");
        btnAbastecer.setEnabled(false);
        btnAbastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbastecerActionPerformed(evt);
            }
        });

        btnLiquidar.setBackground(java.awt.Color.lightGray);
        btnLiquidar.setText("LIQUIDAR");
        btnLiquidar.setEnabled(false);
        btnLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiquidarActionPerformed(evt);
            }
        });

        btnAnular.setBackground(java.awt.Color.lightGray);
        btnAnular.setText("ANULAR");
        btnAnular.setEnabled(false);
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(java.awt.Color.lightGray);
        btnImprimir.setText("IMPRIMIR");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAbastecer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 179, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("PADRON");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 41, -1, -1));

        txtPadron.setPlaceholder("0000");
        txtPadron.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPadronKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPadronKeyReleased(evt);
            }
        });
        jPanel2.add(txtPadron, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 30, 123, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 29, 92, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 360, 100));

        lblnom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnom.setForeground(new java.awt.Color(255, 0, 0));
        lblnom.setText("jLabel2");
        add(lblnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 11, 437, -1));

        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 0, 0));
        lblfecha.setText("jLabel3");
        add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 51, 437, 15));

        lblhora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblhora.setForeground(new java.awt.Color(255, 0, 0));
        lblhora.setText("jLabel3");
        add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 84, 159, 15));

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(0, 0, 255));
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblusuario.setText("jLabel2");
        add(lblusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 87, 247, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tb4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb4MousePressed
        int FilaSelec = tb4.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb4.getValueAt(FilaSelec,0).toString(), "4.00", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb4MousePressed
    private void tb5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb5MousePressed
        int FilaSelec = tb5.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb5.getValueAt(FilaSelec,0).toString(), "5.00", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb5MousePressed
    private void tb3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb3MousePressed
        int FilaSelec = tb3.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb3.getValueAt(FilaSelec,0).toString(), "3.00", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb3MousePressed

    private void tb25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb25MousePressed
        int FilaSelec = tb25.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            System.out.println(tb25.getValueAt(FilaSelec,0).toString());
            String [] datos = CDB.Informacion(tb25.getValueAt(FilaSelec,0).toString(), "2.50", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);

        }
    }//GEN-LAST:event_tb25MousePressed

    private void tb12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb12MousePressed

        int FilaSelec = tb12.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb12.getValueAt(FilaSelec,0).toString(), "1.20", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb12MousePressed
    private void tb1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MousePressed
        int FilaSelec = tb1.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb1.getValueAt(FilaSelec,0).toString(), "1.00", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb1MousePressed

    private void tb1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb1KeyPressed

    }//GEN-LAST:event_tb1KeyPressed

    private void tb15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb15MousePressed
        int FilaSelec = tb15.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb15.getValueAt(FilaSelec,0).toString(), "1.50", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb15MousePressed

    private void tb2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MousePressed
        int FilaSelec = tb2.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb2.getValueAt(FilaSelec,0).toString(), "2.00", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb2MousePressed

    private void tb50MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb50MousePressed
        int FilaSelec = tb50.getSelectedRow();
        if(FilaSelec==-1){
        }else{
            String [] datos = CDB.Informacion(tb50.getValueAt(FilaSelec,0).toString(), "0.50", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb50MousePressed

    private void tb70MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb70MousePressed
        int FilaSelec = tb70.getSelectedRow();
        if(FilaSelec==-1){

        }else{
            String [] datos = CDB.Informacion(tb70.getValueAt(FilaSelec,0).toString(), "0.70", CodigoVehiculo);
            lblnom.setText(datos[0]);
            lblfecha.setText(datos[1]);
            lblusuario.setText(datos[2]);
            lblhora.setText(datos[3]);
        }
    }//GEN-LAST:event_tb70MousePressed

    private void btnAbastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbastecerActionPerformed
        Vista.Boletaje.AbastercerBoletos.CodVehiculo = CodigoVehiculo;
        new  Vista.Boletaje.AbastercerBoletos(null, true).setVisible(true);
    }//GEN-LAST:event_btnAbastecerActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(CV.ExistePadron(txtPadron.getText())){                            
            CodigoVehiculo = CV.Codigo(CV.Placa(txtPadron.getText()));
            Tablas.LimpiarTabla((DefaultTableModel) tb5.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb4.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb3.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb25.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb2.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb15.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb12.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb1.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb70.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb50.getModel());
            
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb5.getModel(),"5.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb4.getModel(),"4.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb3.getModel(),"3.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb25.getModel(),"2.50",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb2.getModel(),"2.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb15.getModel(),"1.50",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb12.getModel(),"1.20",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb1.getModel(),"1.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb70.getModel(),"0.70",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb50.getModel(),"0.50",CodigoVehiculo);
            
            btnImprimir.setEnabled(true);
            btnLiquidar.setEnabled(true);
            btnAbastecer.setEnabled(true);
            btnAnular.setEnabled(true);
            btnImprimir.setBackground(new java.awt.Color(0,112,192));
            btnLiquidar.setBackground(new java.awt.Color(0,112,192));
            btnAbastecer.setBackground(new java.awt.Color(0,112,192));
            btnAnular.setBackground(new java.awt.Color(0,112,192));
               
        }else{
            JOptionPane.showMessageDialog(null,"EL PADRON NO ESTA REGISTRADO","ERROR",0);
            btnImprimir.setEnabled(false);
            btnLiquidar.setEnabled(false);
            btnAbastecer.setEnabled(false);
            btnAnular.setEnabled(false);
            btnImprimir.setBackground(Color.lightGray);
            btnLiquidar.setBackground(Color.lightGray);
            btnAbastecer.setBackground(Color.lightGray);
            btnAnular.setBackground(Color.lightGray);
            CodigoVehiculo = "";
            Tablas.LimpiarTabla((DefaultTableModel) tb5.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb4.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb3.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb25.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb2.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb15.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb12.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb1.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb70.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb50.getModel());
        }
              
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPadronKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPadronKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER|| evt.getKeyCode()==KeyEvent.VK_TAB){
           if(CV.ExistePadron(txtPadron.getText())){                            
            CodigoVehiculo = CV.Codigo(CV.Placa(txtPadron.getText()));
            Tablas.LimpiarTabla((DefaultTableModel) tb5.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb4.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb3.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb25.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb2.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb15.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb12.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb1.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb70.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb50.getModel());
            
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb5.getModel(),"5.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb4.getModel(),"4.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb3.getModel(),"3.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb25.getModel(),"2.50",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb2.getModel(),"2.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb15.getModel(),"1.50",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb12.getModel(),"1.20",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb1.getModel(),"1.00",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb70.getModel(),"0.70",CodigoVehiculo);
            Tablas.LlenarTablaControlBoleto((DefaultTableModel) tb50.getModel(),"0.50",CodigoVehiculo);    
            btnImprimir.setEnabled(true);
            btnLiquidar.setEnabled(true);
            btnAbastecer.setEnabled(true);
            btnAnular.setEnabled(true);
            btnImprimir.setBackground(new java.awt.Color(0,112,192));
            btnLiquidar.setBackground(new java.awt.Color(0,112,192));
            btnAbastecer.setBackground(new java.awt.Color(0,112,192));
            btnAnular.setBackground(new java.awt.Color(0,112,192));
               
        }else{
            JOptionPane.showMessageDialog(null,"EL PADRON NO ESTA REGISTRADO","ERROR",0);
            btnImprimir.setEnabled(false);
            btnLiquidar.setEnabled(false);
            btnAbastecer.setEnabled(false);
            btnAnular.setEnabled(false);
            btnImprimir.setBackground(Color.lightGray);
            btnLiquidar.setBackground(Color.lightGray);
            btnAbastecer.setBackground(Color.lightGray);
            btnAnular.setBackground(Color.lightGray);
            CodigoVehiculo = "";
            Tablas.LimpiarTabla((DefaultTableModel) tb5.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb4.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb3.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb25.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb2.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb15.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb12.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb1.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb70.getModel());
            Tablas.LimpiarTabla((DefaultTableModel) tb50.getModel());            
           }
        }
    }//GEN-LAST:event_txtPadronKeyPressed

    private void btnLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiquidarActionPerformed
        Vista.Boletaje.LiqudacionBoletos.CodVeh = CodigoVehiculo;
        new  Vista.Boletaje.LiqudacionBoletos(null, true).setVisible(true);
    }//GEN-LAST:event_btnLiquidarActionPerformed
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        Imprimir.ImprimirBol.Codigo= CodigoVehiculo;
        Imprimir.ImprimirBol.Padron= txtPadron.getText();
        new  Imprimir.ImprimirBol(null, true).setVisible(false);
        Imprimir.ImprimirBol.Imprimir();
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        Vista.Boletaje.AnularBoleto.Vehiculo = CodigoVehiculo;
        new  Vista.Boletaje.AnularBoleto(null, true).setVisible(true);
    }//GEN-LAST:event_btnAnularActionPerformed

    private void txtPadronKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPadronKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPadronKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnAbastecer;
    private rojeru_san.RSButton btnAnular;
    private rojeru_san.RSButton btnBuscar;
    private rojeru_san.RSButton btnImprimir;
    private rojeru_san.RSButton btnLiquidar;
    private javax.swing.JPanel controlboleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblusuario;
    public static javax.swing.JTable tb1;
    public static javax.swing.JTable tb12;
    public static javax.swing.JTable tb15;
    public static javax.swing.JTable tb2;
    public static javax.swing.JTable tb25;
    public static javax.swing.JTable tb3;
    public static javax.swing.JTable tb4;
    public static javax.swing.JTable tb5;
    public static javax.swing.JTable tb50;
    public static javax.swing.JTable tb70;
    private rojeru_san.RSMTextFull txtPadron;
    // End of variables declaration//GEN-END:variables
}
