
package Vista.Menu;

import Controlador.CambiaPanel;
import static Vista.Menu.Home.pnlPrincipal;
import Vista.Boletaje.*;

public class MenuBoletaje extends javax.swing.JPanel {

    CambiaPanel cambiaPanel;
    public MenuBoletaje() {
        initComponents();
        Home.lblTitulo.setText("MENU VEHICULOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        rSButtonIconD6 = new rojerusan.RSButtonIconD();
        rSButtonIconD7 = new rojerusan.RSButtonIconD();
        jLabel10 = new javax.swing.JLabel();
        rSButtonIconD8 = new rojerusan.RSButtonIconD();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("BUSCAR BOLETO");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, 23));

        rSButtonIconD6.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconD6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONTROLPAGO.png"))); // NOI18N
        rSButtonIconD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD6ActionPerformed(evt);
            }
        });
        add(rSButtonIconD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 174, 143));

        rSButtonIconD7.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte_1.png"))); // NOI18N
        rSButtonIconD7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD7ActionPerformed(evt);
            }
        });
        add(rSButtonIconD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 174, 143));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("DISTRIBUCION DE BOLETO");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, 23));

        rSButtonIconD8.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        rSButtonIconD8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD8ActionPerformed(evt);
            }
        });
        add(rSButtonIconD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 174, 143));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("REPORTE");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, 23));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD6ActionPerformed
        cambiaPanel = new CambiaPanel(pnlPrincipal, new ControlBoletos() );
    }//GEN-LAST:event_rSButtonIconD6ActionPerformed

    private void rSButtonIconD7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD7ActionPerformed
        new  Vista.Boletaje.ReporteProduccionBoleto(null, true).setVisible(true);
    }//GEN-LAST:event_rSButtonIconD7ActionPerformed

    private void rSButtonIconD8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD8ActionPerformed
        new  Vista.Boletaje.BusquedaBioleto(null, true).setVisible(true);
    }//GEN-LAST:event_rSButtonIconD8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private rojerusan.RSButtonIconD rSButtonIconD6;
    private rojerusan.RSButtonIconD rSButtonIconD7;
    private rojerusan.RSButtonIconD rSButtonIconD8;
    // End of variables declaration//GEN-END:variables
}
